version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "${ELEVATOR_FRONTEND_PORT}:8080"
    env_file:
      - ele_front.env
    depends_on:
      - elevator
  elevator:
    build: .
    ports:
      - "${ELEVATOR_PORT}:8080"
    env_file:
      - ele.env
